/*
Copyright 2026 The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package cachekey derives a SourceDefinition's cache key from the context its
// template reads.
//
// The key is generated at build time by `vela def` and validated at admission, so
// nothing infers at reconcile time: the controller evaluates the generated
// expression exactly as it would an authored one.
//
// Policy - which fields count, in what order - lives in an embedded CUE file whose
// hash is the version identity. Mechanism lives here.
package cachekey

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"fmt"
	"sort"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
)

//go:embed rules/*.cue
var rulesFS embed.FS

// keyedField is a context field that contributes to the key.
type keyedField struct {
	Order   int  `json:"order"`
	Indexed bool `json:"indexed"`
}

// Rules is one version of the inference policy, identified by the hash of the
// file it was loaded from.
type Rules struct {
	// Hash identifies this policy. It is stamped onto generated definitions and
	// used to load the same rules again when validating them.
	Hash string

	keyed     map[string]keyedField
	forbidden map[string]string
}

// LoadRules returns the current rules - the latest file in the embedded set.
func LoadRules() (*Rules, error) {
	names, err := ruleFileNames()
	if err != nil {
		return nil, err
	}
	return loadRuleFile(names[len(names)-1])
}

// LoadRulesByHash returns the rules with the given hash, for validating a
// definition generated against an earlier policy. A missing hash is an error
// rather than a fallback: silently validating against different rules than the
// ones used to generate would defeat the point of recording it.
func LoadRulesByHash(hash string) (*Rules, error) {
	names, err := ruleFileNames()
	if err != nil {
		return nil, err
	}
	for _, name := range names {
		r, err := loadRuleFile(name)
		if err != nil {
			return nil, err
		}
		if r.Hash == hash {
			return r, nil
		}
	}
	return nil, fmt.Errorf("no cache-key rules with hash %q are embedded in this build; "+
		"the definition was generated by a version whose rules are not present", hash)
}

func ruleFileNames() ([]string, error) {
	entries, err := rulesFS.ReadDir("rules")
	if err != nil {
		return nil, fmt.Errorf("reading embedded rules: %w", err)
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() {
			names = append(names, "rules/"+e.Name())
		}
	}
	if len(names) == 0 {
		return nil, fmt.Errorf("no cache-key rules are embedded in this build")
	}
	sort.Strings(names)
	return names, nil
}

func loadRuleFile(name string) (*Rules, error) {
	raw, err := rulesFS.ReadFile(name)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", name, err)
	}

	sum := sha256.Sum256(raw)
	rules := &Rules{
		Hash:      hex.EncodeToString(sum[:])[:8],
		keyed:     map[string]keyedField{},
		forbidden: map[string]string{},
	}

	v := cuecontext.New().CompileBytes(raw)
	if v.Err() != nil {
		return nil, fmt.Errorf("compiling %s: %w", name, v.Err())
	}
	if err := v.LookupPath(cue.ParsePath("keyed")).Decode(&rules.keyed); err != nil {
		return nil, fmt.Errorf("decoding keyed fields from %s: %w", name, err)
	}
	if err := v.LookupPath(cue.ParsePath("forbidden")).Decode(&rules.forbidden); err != nil {
		return nil, fmt.Errorf("decoding forbidden fields from %s: %w", name, err)
	}
	return rules, nil
}

// IsClassified reports whether these rules make a decision about a context field.
// Anything unclassified is rejected in a source template: failing closed means a
// field added later cannot silently become an unkeyed dependency.
func (r *Rules) IsClassified(field string) bool {
	if _, ok := r.keyed[field]; ok {
		return true
	}
	_, ok := r.forbidden[field]
	return ok
}

// forbiddenReason returns why a field may not be read, and whether it is forbidden.
func (r *Rules) forbiddenReason(field string) (string, bool) {
	reason, ok := r.forbidden[field]
	return reason, ok
}

// keyedField returns the ordering entry for a field, and whether it is keyed.
func (r *Rules) keyedEntry(field string) (keyedField, bool) {
	e, ok := r.keyed[field]
	return e, ok
}
