// Cache-key inference rules.
//
// This file is POLICY: it decides which context fields a SourceDefinition's cache
// key is built from, and in what order. The mechanism - scanning the template and
// assembling the key - lives in Go.
//
// DO NOT EDIT THIS FILE.
//
// Its hash is the version identity stamped onto every definition generated with
// it, and validation loads the rules an object was stamped with. Editing it
// changes the hash, so definitions stamped with the old hash would no longer find
// their rules. To change the policy, add a new file alongside this one; this one
// must remain for as long as any definition references it.

// version: a readable name for this policy, for correlating a stamped definition
// with the rules that produced it without computing hashes. The hash remains the
// identity - this is for the human reading the annotation.
version: "v1"

// keyed: fields that contribute to the cache key, lowest order first.
//
// Ordered broad to narrow so keys group by prefix when listed: an operator
// grepping for a definition on a cluster finds every entry under it. Consumer
// identity sorts last, so a source that does not read it keeps a key shared
// across components.
keyed: {
	cluster: order:        1
	clusterVersion: order: 2

	namespace: order:      3
	appName: order:        4
	appRevision: order:    5
	appRevisionNum: order: 6
	publishVersion: order: 7
	workflowName: order:   8

	// Indexed: the read carries a literal key, and that key's value is what
	// contributes. Entries are ordered by index so two reads assemble the same
	// way every time.
	appLabels: {order:      9, indexed: true}
	appAnnotations: {order: 10, indexed: true}

	// Consumer identity. A source may depend on which component consumed it -
	// a component name used as the identifier it queries by, say - and when it
	// does, the key says so.
	name: order:          11
	componentType: order: 12
	revision: order:      13
	replicaKey: order:    14
}

// forbidden: reading these in a source template fails admission. The value is the
// reason, and it is shown in the rejection.
forbidden: {
	// Populated only when rendering a policy, so a source reading them during a
	// component render gets nothing useful.
	policyName:         "policy context is not populated during a component render"
	policyType:         "policy context is not populated during a component render"
	policyRevisionName: "policy context is not populated during a component render"
	policyRevision:     "policy context is not populated during a component render"
	policyRevisionHash: "policy context is not populated during a component render"

	// Structures rather than identifiers: too large to key on, and not stable.
	appComponents: "not a stable identifier; key on the fields you need instead"
	appWorkflow:   "not a stable identifier; key on the fields you need instead"
	appPolicies:   "not a stable identifier; key on the fields you need instead"
	components:    "not a stable identifier; key on the fields you need instead"
	artifacts:     "not a stable identifier; key on the fields you need instead"

	// The source machinery itself. appSourceCacheStore is a live Go object, not
	// data, and the rest describe the resolution in progress.
	appSources:               "internal to source resolution"
	appSourceTypes:           "internal to source resolution"
	appSourceTemplates:       "internal to source resolution"
	appSourceSensitivePaths:  "internal to source resolution"
	appSourceCacheStore:      "internal to source resolution"
}
