// Cache-key inference rules.
//
// This file is POLICY: it decides which context a SourceDefinition may read, and
// in what order each contributes to the cache key. The mechanism - scanning the
// template, assembling the key, and building the context a source is compiled
// against - lives in Go and is driven entirely by the list below.
//
// DO NOT EDIT THIS FILE.
//
// The hash of `keyed` is the version identity stamped onto every definition
// generated with it, and validation loads the rules an object was stamped with.
// Changing `keyed` changes the hash, so definitions stamped with the old one would
// no longer find their rules. To change the policy, add a new file alongside this
// one; this one must remain for as long as any definition references it.

// version: a readable name for this policy, for correlating a stamped definition
// with the rules that produced it without computing hashes. The hash remains the
// identity - this is for the human reading the annotation.
version: "v1"

// keyed: the context a source template may read, and the order each contributes
// to the cache key.
//
// Anything absent is unsupported: rejected at admission, and not present in the
// context a source is compiled against, so it cannot be read even where admission
// is disabled. Data that is not here reaches a source as a property instead.
//
// The assembled key is:
//
//	<definition>[-<binding>][-<context dimensions...>][-<properties hash>]
//
// Identity leads - the definition, then the binding entry it was declared as.
// Context dimensions follow broad to narrow, so keys group by prefix when listed:
// an operator grepping for a definition on a cluster finds every entry under it.
keyed: {
	// The spec.sources[] entry this binding was declared as - the instance, in the
	// sense context.name carries everywhere else in KubeVela. Not the
	// SourceDefinition, which is already the key's prefix.
	name: order: 1

	cluster: order:        2
	clusterVersion: order: 3

	namespace: order:      4
	appName: order:        5
	appRevision: order:    6
	appRevisionNum: order: 7
	publishVersion: order: 8
	workflowName: order:   9

	// Indexed: the read carries a literal key, and that key's value is what
	// contributes. Entries are ordered by index so two reads assemble the same
	// way every time.
	appLabels: {order:      10, indexed: true}
	appAnnotations: {order: 11, indexed: true}
}
