// Cache-key inference rules.
//
// This file is POLICY: it decides which context a SourceDefinition may read, and
// in what order each contributes to the cache key. The mechanism - scanning the
// template, assembling the key, and building the context a source is compiled
// against - lives in Go and is driven entirely by the list below.
//
// DO NOT EDIT THIS FILE - once this feature has shipped.
//
// The hash of `keyed` is the version identity stamped onto every definition
// generated with it, and validation loads the rules an object was stamped with.
// Changing `keyed` changes the hash, so definitions stamped with the old one would
// no longer find their rules. To change the policy after release, add a new file
// alongside this one; this one must remain for as long as any definition
// references it.
//
// Before release the rule does not bite: nothing outside this repository has ever
// been stamped, so editing in place and regenerating our own definitions is
// simpler than carrying a version nobody needs. LoadRulesByHash and the multiple-
// file layout stay, because they are what makes the first real change safe.

// version: a readable name for this policy, for correlating a stamped definition
// with the rules that produced it without computing hashes. The hash remains the
// identity - this is for the human reading the annotation.
version: "v1"

// keyed: the context a source template may read, and the order each contributes
// to the cache key.
//
// Anything absent is unsupported: rejected at admission, and not present in the
// context a source is compiled against, so it cannot be read even where admission
// is disabled. Data that is not here reaches a source as a property instead.
//
// The assembled identity is:
//
//	<definition>[-<readable segments...>]-<hash>
//
// The hash covers every value the template reads, and carries uniqueness on its
// own. Segments are cosmetic: they exist so an operator can grep, and an empty one
// is simply dropped - two identities differing only in a dropped segment still
// differ in the hash. `segment: true` therefore says nothing about correctness,
// only about what is worth reading.
//
// A field is inlined only if it is always renderable: a Kubernetes name, not a
// struct, not a free-form value. clusterVersion is a struct; label and annotation
// values may contain characters that are legal there and illegal in an object
// name. Those contribute to the hash alone.
keyed: {
	// The spec.sources[] entry this binding was declared as - the instance, in the
	// sense context.name carries everywhere else in KubeVela. Not the
	// SourceDefinition, which is already the key's prefix.
	name: {order: 1, segment: true}

	cluster: {order: 2, segment: true}
	// A struct - {major, minor, gitVersion, platform} - so it cannot be rendered
	// into a name at all.
	clusterVersion: order: 3

	namespace: {order: 4, segment: true}
	appName: {order:   5, segment: true}

	// Legitimately empty in normal operation - appRevision before the first
	// revision exists, publishVersion and workflowName unless set - so they are
	// hashed rather than inlined, and their absence needs no sentinel.
	appRevision: order:    6
	appRevisionNum: order: 7
	publishVersion: order: 8
	workflowName: order:   9

	// Indexed: the read carries a literal key, and that key's value is what
	// contributes. Entries are ordered by index so two reads assemble the same
	// way every time.
	appLabels: {order:      10, indexed: true}
	appAnnotations: {order: 11, indexed: true}
}
